# Generated by Django 3.1.1 on 2020-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='ngo',
            field=models.ManyToManyField(to='accounts.Ngo'),
        ),
    ]
