# Generated by Django 3.1.1 on 2020-09-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200926_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('donator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.donator')),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.ngo')),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.requirement')),
            ],
        ),
    ]
