# Generated by Django 3.1.1 on 2020-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_donationdetail_donator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
