# Generated by Django 3.1.1 on 2020-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200929_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donator',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donator',
            name='phone',
            field=models.CharField(default='-1', max_length=10, unique=True),
        ),
    ]
