# Generated by Django 3.1.1 on 2020-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200930_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
