# Generated by Django 3.0.6 on 2020-10-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200930_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdetail',
            old_name='req',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='ngorequirementdetail',
            old_name='req',
            new_name='requirement',
        ),
    ]
