# Generated by Django 3.0.6 on 2020-10-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201010_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdetail',
            old_name='requirement',
            new_name='req',
        ),
        migrations.RenameField(
            model_name='ngorequirementdetail',
            old_name='requirement',
            new_name='req',
        ),
    ]
